[theme]
base            = "dark"
backgroundColor         = "#c8d3ea"
secondaryBackgroundColor = "#142b4c"
textColor       = "#f8fafc"
primaryColor    = "#e8f1f2"
font            = "sans serif"

[browser]
gatherUsageStats = false
